//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDR_MAINMENU                    101
#define IDI_MIRANDA                     102
#define IDD_ABOUT                       103
#define IDI_ONLINE                      104
#define IDI_OFFLINE                     105
#define IDD_MSGRECV                     107
#define IDD_MSGSEND                     108
#define IDD_ADDCONTACT1                 109
#define IDD_GNUPL                       110
#define IDD_PASSWORD                    111
#define IDI_TRAY                        113
#define IDI_TRAYICON                    114
#define IDI_TRAYICON_OLD                114
#define IDD_ADDED                       115
#define IDD_EASYTALK                    117
#define IDD_SENDURL                     119
#define IDD_URLRECV                     120
#define IDD_AUTHREQ                     121
#define IDD_ADDCONTACT2                 122
#define IDD_RESULTS                     123
#define IDD_ADDCONTACT3                 124
#define IDD_DETAILS                     125
#define IDD_GENERALOPT                  126
#define IDD_HISTORY                     127
#define IDI_AWAY                        128
#define IDI_FREE4CHAT                   129
#define IDI_INVISIBLE                   130
#define IDI_NA                          131
#define IDI_TRAYOFFL                    132
#define IDI_TRAYOFFL_OLD                132
#define IDD_SOUND                       134
#define IDI_SENDURL                     135
#define IDI_RECVMSG                     136
#define IDI_SENDMSG                     137
#define IDI_RECVURL                     138
#define IDI_NA2                         139
#define IDI_TRAYOFFLINE                 140
#define IDI_TRAYONLINE                  141
#define IDD_PROXY                       142
#define IDD_DIALOG1                     143
#define IDI_AWAY2                       144
#define IDI_FREE4CHAT2                  145
#define IDI_UNREAD                      147
#define IDB_TITLE                       150
#define IDB_OPTIONS_GEN                 151
#define IDB_OPTIONS_PASSWORD            152
#define IDB_DETAILS                     153
#define IDB_MSG_RECV                    154
#define IDB_MSG_SEND                    155
#define IDB_CONTACT_ADD                 156
#define IDB_URL_SEND                    157
#define IDI_DND                         158
#define IDI_OCCUPIED                    159
#define IDI_USERDETAILS                 160
#define IDI_FINDUSER                    161
#define IDI_HELP                        162
#define IDI_OPTIONS                     163
#define IDI_CHECKFORUPGRADE             164
#define IDI_OPTIONS_PROXY               166
#define IDI_OPTIONS_SOUND               167
#define IDI_OPTIONS_PLUGINS             168
#define IDI_OPTIONS_GENERAL             169
#define IDI_OPTIONS_ICQNPASSWORD        170
#define IDI_UNREAD2                     171
#define IDI_MIRANDAWEBSITE              172
#define IDI_RENAME                      173
#define IDI_HISTORY                     174
#define IDI_DELETE                      175
#define IDI_IGNORE                      176
#define IDI_IMPORT                      177
#define IDR_ACCEL                       179
#define IDR_CONTEXT                     180
#define IDC_FROM                        1005
#define IDC_DATE                        1006
#define IDC_MSG                         1008
#define IDC_NAME                        1009
#define IDC_BODY                        1010
#define IDC_ICQ                         1011
#define IDC_TEXT                        1019
#define IDC_PASSWORD                    1020
#define IDC_ICQNUM                      1022
#define IDC_AMES                        1026
#define IDC_RIH                         1027
#define IDC_ANET                        1028
#define IDC_USTAT                       1029
#define IDC_RINH                        1030
#define IDC_PWM                         1031
#define IDC_ABOUT                       1032
#define IDC_CONFIG                      1033
#define IDC_URLS                        1037
#define IDC_REPLY                       1039
#define IDC_URL                         1041
#define IDC_REASON                      1046
#define IDC_EMAIL                       1048
#define IDC_CONTACTS                    1049
#define IDC_NICK                        1053
#define IDC_FIRST                       1054
#define IDC_LAST                        1055
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_AGE                         1064
#define IDC_PHONE                       1065
#define IDC_HP                          1066
#define IDC_GO                          1067
#define IDC_GO2                         1068
#define IDC_DETAILS                     1069
#define IDC_ADD                         1070
#define IDC_MIN2TRAY                    1073
#define IDC_ONTOP                       1074
#define IDC_POPUP                       1075
#define IDC_TRANSP                      1076
#define IDC_EDIT                        1078
#define IDC_LIST                        1079
#define IDC_HISTORY                     1080
#define IDC_EBAC                        1083
#define IDC_MEGAHAL                     1084
#define IDC_USESOUND                    1085
#define IDC_SOUND1                      1086
#define IDC_B1                          1087
#define IDC_SOUND2                      1088
#define IDC_USE                         1088
#define IDC_B2                          1089
#define IDC_HOST                        1089
#define IDC_SOUND3                      1090
#define IDC_PORT                        1090
#define IDC_B3                          1091
#define IDC_AUTH                        1091
#define IDC_SOUND4                      1092
#define IDC_B4                          1093
#define IDC_PASS                        1093
#define IDC_SOUND5                      1094
#define IDC_IP                          1094
#define IDC_B5                          1095
#define IDC_USEINI                      1095
#define IDC_SOUND6                      1096
#define IDC_B6                          1097
#define IDC_TOOLWND                     1097
#define IDC_SOUND7                      1098
#define IDC_ONECLK                      1098
#define IDC_B7                          1099
#define IDC_SOUND8                      1100
#define IDC_B8                          1101
#define IDC_SOUND9                      1102
#define IDC_B9                          1103
#define ID_ICQ_EX                       40001
#define ID_ICQ_STATUS_ONLINE            40003
#define ID_ICQ_STATUS_AWAY              40005
#define ID_ICQ_STATUS_DND               40006
#define ID_ICQ_STATUS_NA                40007
#define ID_ICQ_STATUS_OCCUPIED          40008
#define ID_ICQ_STATUS_FREECHAT          40009
#define ID_ICQ_STATUS_INVISIBLE         40010
#define ID_HELP_ABOUT                   40011
#define ID_ICQ_STATUS_OFFLINE           40012
#define ID_ICQ_ADDCONTACT               40013
#define ID_ICQ_ADDCONTACT_BYICQ         40014
#define ID_ICQ_ADDCONTACT_BYEMAIL       40015
#define ID_ICQ_ADDCONTACT_BYNAME        40016
#define ID_ICQ_OPTIONS                  40017
#define ID_ICQ_OPTIONS_ICQPASSWORD      40018
#define ID_ICQ_OPTIONS_SPEECHOPTIONS    40019
#define ID_ICQ_VIEWDETAILS              40020
#define ID_ICQ_OPTIONS_GENERALOPTIONS   40021
#define ID_HELP_CKECKFORUPGRADES        40022
#define ID_ICQ_OPTIONS_SOUNDOPTIONS     40023
#define ID_ICQ_OPTIONS_PROXYSETTINGS    40024
#define ID_ICQ_OPTIONS_PLUGINS          40025
#define ID_HELP_WINDEX                  40030
#define ID_HELP_MIRANDAWEBSITE          40031
#define ID_ICQ_ADDCONTACT_IMPORT        40032
#define ID_ICQ_PLUGINSETTINGS_NOPLUGINS 40036
#define ID_CTRLENTER                    40037
#define ID_TRAY_HIDE                    40038
#define ID_TRAY_ABOUT                   40039
#define ID_TRAY_EXIT                    40040
#define POPUP_SENDMSG                   40041
#define POPUP_SENDURL                   40042
#define POPUP_HISTORY                   40043
#define POPUP_USERDETAILS               40044
#define POPUP_IGNORE                    40045
#define POPUP_RENAME                    40046
#define POPUP_DELETE                    40047

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         40048
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
